-- Meryl Shoes Enterprise System
-- ERD + Data Dictionary aligned schema
-- Uses the current database naming style where practical, while aligning
-- entities and attributes to the provided ERD and document.
-- Run in Supabase SQL Editor.

begin;

DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS prediction_history CASCADE;
DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS sales_summary CASCADE;
DROP TABLE IF EXISTS inventory_log CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS return_details CASCADE;
DROP TABLE IF EXISTS returns CASCADE;
DROP TABLE IF EXISTS prediction CASCADE;
DROP TABLE IF EXISTS sales_analytics CASCADE;
DROP TABLE IF EXISTS sales_details CASCADE;
DROP TABLE IF EXISTS sales_transaction CASCADE;
DROP TABLE IF EXISTS promo_product CASCADE;
DROP TABLE IF EXISTS promotion CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS category CASCADE;

CREATE TABLE role (
    role_id bigint generated by default as identity primary key,
    role_name varchar(50) not null unique
);

CREATE TABLE users (
    user_id bigint generated by default as identity primary key,
    name varchar(100) not null,
    username varchar(50) not null unique,
    password varchar(255) not null,
    role_id bigint not null references role(role_id) on delete restrict,
    status varchar(20) not null default 'Active',
    CONSTRAINT users_status_check CHECK (status in ('Active', 'Inactive', 'Blocked'))
);

CREATE TABLE customers (
    customer_id bigint generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(100),
    contact_number varchar(15),
    date_registered date not null default current_date,
    CONSTRAINT customers_email_unique UNIQUE (email)
);

CREATE TABLE category (
    category_id bigint generated by default as identity primary key,
    category_name varchar(100) not null unique
);

CREATE TABLE product (
    product_id bigint generated by default as identity primary key,
    product_name varchar(150) not null,
    category_id bigint not null references category(category_id) on delete restrict,
    brand varchar(100) not null,
    size varchar(30) not null,
    color varchar(50) not null,
    cost_price numeric(12,2) not null default 0,
    reorder_level integer not null default 10,
    status varchar(20) not null default 'Available',
    CONSTRAINT product_cost_price_check CHECK (cost_price >= 0),
    CONSTRAINT product_reorder_level_check CHECK (reorder_level >= 0),
    CONSTRAINT product_status_check CHECK (status in ('Available', 'Not Available', 'Discontinued'))
);

CREATE TABLE inventory (
    inventory_id bigint generated by default as identity primary key,
    product_id bigint not null unique references product(product_id) on delete cascade,
    stock_quantity integer not null default 0,
    reorder_level integer not null default 10,
    reference_id bigint,
    last_updated timestamptz not null default now(),
    CONSTRAINT inventory_stock_quantity_check CHECK (stock_quantity >= 0),
    CONSTRAINT inventory_reorder_level_check CHECK (reorder_level >= 0)
);

CREATE TABLE promotion (
    promo_id bigint generated by default as identity primary key,
    promo_name varchar(150) not null,
    discount_type varchar(30) not null,
    discount_value numeric(12,2) not null default 0,
    start_date date not null,
    end_date date not null,
    status varchar(20) not null default 'Active',
    CONSTRAINT promotion_discount_type_check CHECK (discount_type in ('Percentage', 'Fixed Amount', 'BOGO')),
    CONSTRAINT promotion_discount_value_check CHECK (discount_value >= 0),
    CONSTRAINT promotion_status_check CHECK (status in ('Active', 'Scheduled', 'Inactive')),
    CONSTRAINT promotion_date_check CHECK (end_date >= start_date)
);

CREATE TABLE promo_product (
    promo_product_id bigint generated by default as identity primary key,
    promo_id bigint not null references promotion(promo_id) on delete cascade,
    product_id bigint not null references product(product_id) on delete cascade,
    CONSTRAINT promo_product_unique UNIQUE (promo_id, product_id)
);

CREATE TABLE sales_transaction (
    sales_id bigint generated by default as identity primary key,
    customer_id bigint references customers(customer_id) on delete set null,
    transaction_date timestamptz not null default now(),
    total_amount numeric(12,2) not null default 0,
    payment_method varchar(30) not null,
    user_id bigint not null references users(user_id) on delete restrict,
    CONSTRAINT sales_transaction_total_amount_check CHECK (total_amount >= 0),
    CONSTRAINT sales_transaction_payment_method_check CHECK (payment_method in ('Cash', 'GCash', 'Card'))
);

CREATE TABLE payment (
    payment_id bigint generated by default as identity primary key,
    sales_id bigint not null unique references sales_transaction(sales_id) on delete cascade,
    payment_method varchar(30) not null,
    amount_paid numeric(12,2) not null default 0,
    change_amount numeric(12,2) not null default 0,
    payment_status varchar(20) not null default 'Pending',
    CONSTRAINT payment_amount_paid_check CHECK (amount_paid >= 0),
    CONSTRAINT payment_change_amount_check CHECK (change_amount >= 0),
    CONSTRAINT payment_method_check CHECK (payment_method in ('Cash', 'GCash', 'Card')),
    CONSTRAINT payment_status_check CHECK (payment_status in ('Pending', 'Paid', 'Failed', 'Refunded'))
);

CREATE TABLE sales_details (
    sales_detail_id bigint generated by default as identity primary key,
    sales_id bigint not null references sales_transaction(sales_id) on delete cascade,
    product_id bigint not null references product(product_id) on delete restrict,
    quantity integer not null default 1,
    price numeric(12,2) not null default 0,
    discount_applied numeric(12,2) not null default 0,
    subtotal numeric(12,2) not null default 0,
    CONSTRAINT sales_details_quantity_check CHECK (quantity > 0),
    CONSTRAINT sales_details_price_check CHECK (price >= 0),
    CONSTRAINT sales_details_discount_check CHECK (discount_applied >= 0),
    CONSTRAINT sales_details_subtotal_check CHECK (subtotal >= 0)
);

CREATE TABLE inventory_log (
    inventory_log_id bigint generated by default as identity primary key,
    product_id bigint not null references product(product_id) on delete cascade,
    quantity_change integer not null,
    transaction_type varchar(30) not null,
    reference_id bigint,
    date_updated timestamptz not null default now(),
    CONSTRAINT inventory_log_transaction_type_check CHECK (
        transaction_type in ('Stock In', 'Stock Out', 'Sale', 'Adjustment', 'Return', 'Restock')
    )
);

CREATE TABLE sales_analytics (
    analytics_id bigint generated by default as identity primary key,
    product_id bigint not null references product(product_id) on delete cascade,
    total_sales numeric(12,2) not null default 0,
    total_quantity_sold integer not null default 0,
    average_sales numeric(12,2) not null default 0,
    ranking integer,
    trend_type varchar(20) not null default 'Steady',
    time_period varchar(20) not null default 'Monthly',
    CONSTRAINT sales_analytics_total_sales_check CHECK (total_sales >= 0),
    CONSTRAINT sales_analytics_total_quantity_sold_check CHECK (total_quantity_sold >= 0),
    CONSTRAINT sales_analytics_average_sales_check CHECK (average_sales >= 0),
    CONSTRAINT sales_analytics_ranking_check CHECK (ranking is null or ranking > 0),
    CONSTRAINT sales_analytics_trend_type_check CHECK (trend_type in ('Rising', 'Steady', 'Declining')),
    CONSTRAINT sales_analytics_time_period_check CHECK (time_period in ('Daily', 'Weekly', 'Monthly', 'Yearly'))
);

CREATE TABLE sales_summary (
    summary_id bigint generated by default as identity primary key,
    total_revenue numeric(12,2) not null default 0,
    total_transaction integer not null default 0,
    total_item_sold integer not null default 0,
    summary_date date not null default current_date,
    CONSTRAINT sales_summary_total_revenue_check CHECK (total_revenue >= 0),
    CONSTRAINT sales_summary_total_transaction_check CHECK (total_transaction >= 0),
    CONSTRAINT sales_summary_total_item_sold_check CHECK (total_item_sold >= 0),
    CONSTRAINT sales_summary_summary_date_unique UNIQUE (summary_date)
);

CREATE TABLE prediction (
    prediction_id bigint generated by default as identity primary key,
    product_id bigint not null references product(product_id) on delete cascade,
    predicted_demand integer not null default 0,
    prediction_period varchar(20) not null,
    prediction_date date not null default current_date,
    CONSTRAINT prediction_predicted_demand_check CHECK (predicted_demand >= 0),
    CONSTRAINT prediction_period_check CHECK (prediction_period in ('Daily', 'Weekly', 'Monthly', 'Yearly'))
);

CREATE TABLE prediction_history (
    history_id bigint generated by default as identity primary key,
    prediction_id bigint not null references prediction(prediction_id) on delete cascade,
    actual_sales numeric(12,2) not null default 0,
    prediction_accuracy numeric(5,2) not null default 0,
    CONSTRAINT prediction_history_actual_sales_check CHECK (actual_sales >= 0),
    CONSTRAINT prediction_history_accuracy_check CHECK (prediction_accuracy >= 0 and prediction_accuracy <= 100)
);

CREATE TABLE notification (
    notification_id bigint generated by default as identity primary key,
    customer_id bigint not null references customers(customer_id) on delete cascade,
    promo_id bigint not null references promotion(promo_id) on delete cascade,
    email varchar(100) not null,
    email_status varchar(20) not null default 'Pending',
    date_sent timestamptz,
    CONSTRAINT notification_status_check CHECK (email_status in ('Pending', 'Sent', 'Failed'))
);

CREATE TABLE returns (
    return_id bigint generated by default as identity primary key,
    sales_id bigint not null references sales_transaction(sales_id) on delete cascade,
    user_id bigint not null references users(user_id) on delete restrict,
    return_date timestamptz not null default now(),
    total_refund numeric(12,2) not null default 0,
    CONSTRAINT returns_total_refund_check CHECK (total_refund >= 0)
);

CREATE TABLE return_details (
    return_detail_id bigint generated by default as identity primary key,
    return_id bigint not null references returns(return_id) on delete cascade,
    product_id bigint not null references product(product_id) on delete restrict,
    quantity_returned integer not null default 1,
    reason varchar(255),
    refund_amount numeric(12,2) not null default 0,
    CONSTRAINT return_details_quantity_check CHECK (quantity_returned > 0),
    CONSTRAINT return_details_refund_amount_check CHECK (refund_amount >= 0)
);

CREATE INDEX idx_users_role_id ON users(role_id);
CREATE INDEX idx_customers_name ON customers(name);
CREATE INDEX idx_product_category_id ON product(category_id);
CREATE INDEX idx_inventory_product_id ON inventory(product_id);
CREATE INDEX idx_sales_transaction_customer_id ON sales_transaction(customer_id);
CREATE INDEX idx_sales_transaction_user_id ON sales_transaction(user_id);
CREATE INDEX idx_sales_details_sales_id ON sales_details(sales_id);
CREATE INDEX idx_sales_details_product_id ON sales_details(product_id);
CREATE INDEX idx_inventory_log_product_id ON inventory_log(product_id);
CREATE INDEX idx_promo_product_promo_id ON promo_product(promo_id);
CREATE INDEX idx_promo_product_product_id ON promo_product(product_id);
CREATE INDEX idx_sales_analytics_product_id ON sales_analytics(product_id);
CREATE INDEX idx_prediction_product_id ON prediction(product_id);
CREATE INDEX idx_prediction_history_prediction_id ON prediction_history(prediction_id);
CREATE INDEX idx_notification_customer_id ON notification(customer_id);
CREATE INDEX idx_notification_promo_id ON notification(promo_id);
CREATE INDEX idx_returns_sales_id ON returns(sales_id);
CREATE INDEX idx_return_details_return_id ON return_details(return_id);

INSERT INTO role (role_name)
VALUES
    ('Administrator'),
    ('Sales Staff'),
    ('Inventory Staff');

INSERT INTO category (category_name)
VALUES
    ('Running Shoes'),
    ('Basketball Shoes'),
    ('Casual Shoes'),
    ('Sandals'),
    ('Kid'),
    ('Men'),
    ('Women');

commit;
